/**
 * Biblioteca de Ícones Mandato Digital
 * Combinação: Fluent UI (Microsoft) + Govicons (governo/política)
 */

// ============================================
// FLUENT UI — Ícones de Sistema
// ============================================
export {
  PeopleRegular as Users,
  PersonRegular as User,
  PersonAddRegular as UserPlus,
  LocationRegular as MapPin,
  MailRegular as Mail,
  ChatRegular as MessageSquare,
  CommentRegular as MessageCircle,
  DataTrendingRegular as TrendingUp,
  ChartMultipleRegular as BarChart3,
  SearchRegular as Search,
  EditRegular as Pencil,
  EyeRegular as Eye,
  EyeOffRegular as EyeOff,
  ArrowDownloadRegular as Download,
  ArrowUploadRegular as Upload,
  SaveRegular as Save,
  FilterRegular as Filter,
  NavigationRegular as Navigation,
  NavigationUnreadRegular as Menu,
  SettingsRegular as Settings,
  AlertRegular as AlertTriangle,
  WarningRegular as AlertCircle,
  ShieldRegular as Shield,
  FlagRegular as Flag,
  StarRegular as Star,
  CalendarRegular as Calendar,
  CalendarLtrRegular as CalendarDays,
  CalendarWeekNumbersRegular as CalendarRange,
  DocumentRegular as FileText,
  DocumentBulletListRegular as File,
  FolderRegular as FolderOpen,
  ImageRegular as Image,
  PhoneRegular as Phone,
  VideoRegular as Video,
  CameraRegular as Camera,
  GiftRegular as Gift,
  HeartRegular as Heart,
  ThumbLikeRegular as HeartHandshake,
  LockClosedRegular as Lock,
  LinkRegular as Link2,
  ShareRegular as Share2,
  SendRegular as Send,
  ClockRegular as Clock,
  CopyRegular as Copy,
  TagRegular as Tag,
  TargetRegular as Target,
  CheckmarkRegular as Check,
  CheckmarkCircleRegular as CheckCircle,
  CheckmarkCircleRegular as CheckCircle2,
  DismissRegular as X,
  DismissCircleRegular as XCircle,
  DeleteRegular as Trash2,
  AddRegular as Plus,
  ChevronDownRegular as ChevronDown,
  ChevronLeftRegular as ChevronLeft,
  ChevronRightRegular as ChevronRight,
  ChevronUpRegular as ChevronUp,
  HomeRegular as LayoutDashboard,
  BuildingRegular as Building2,
  MapRegular as MapPinned,
  GlobeRegular as ExternalLink,
  MoreHorizontalRegular as MoreHorizontal,
  MoreVerticalRegular as MoreVertical,
  LightbulbRegular as Zap,
  WeatherSunnyRegular as PartyPopper,
  CloudRegular as Layers,
  DatabaseRegular as FileSpreadsheet,
  ServerRegular as Route,
  HeadphonesRegular as Headphones,
  ArrowLeftRegular as ArrowLeft,
  ArrowRightRegular as ArrowRight,
  ArrowUpRegular as ArrowUp,
  ArrowDownRegular as ArrowDown,
  SubtractRegular as Minus,
  SignOutRegular as LogOut,
  ServiceBellRegular as Bell,
  ClipboardTaskRegular as ClipboardList,
  CrownRegular as Crown,
  MedalRegular as Medal,
  TrophyRegular as Award,
  TemperatureRegular as Thermometer,
  ArrowUpRightRegular as ArrowUpRight,
  ArrowUpLeftRegular as ArrowUpLeft,
  SpinnerIosRegular as Loader2,
  ReadingModeMobileRegular as Smartphone,
} from "@fluentui/react-icons";

// ============================================
// GOVICONS — Ícones Temáticos de Governo
// ============================================
export {
  GovIcon,
  IconVote as Vote,
  IconGavel as Gavel,
  IconHandshake as Handshake,
  IconPolitician as Politician,
  IconCapitol as Capitol,
  IconWhiteHouse as WhiteHouse,
  IconBalance as Balance,
  IconMedalStar as MedalStar,
  IconMedalCircle as MedalCircle,
  IconRibbon as RibbonGov,
  IconFlagWavy as FlagWavy,
  IconFlagStraight as FlagStraight,
  IconUSMap as USMap,
  IconWorld as WorldGov,
  IconGovShield as GovShield,
  IconIDCard as IDCard,
  IconFingerprint as Fingerprint,
  IconMoney as Money,
  IconUSD as USD,
  IconPieChart as PieChart,
  IconBarChart as BarChart,
  IconLineChart as LineChart,
  IconGovDatabase as GovDatabase,
  IconGovCloud as GovCloud,
  IconGovSearch as GovSearch,
  IconComment as CommentGov,
  IconComments as CommentsGov,
  IconGovCheck as GovCheck,
  IconGovCheckSquare as GovCheckSquare,
  IconGovWarning as GovWarning,
  IconGovKey as GovKey,
  IconGovFolder as GovFolder,
  IconGovTable as GovTable,
  IconGovUnlock as GovUnlock,
  IconGovLock as GovLock,
  IconGovCog as GovCog,
  IconGovCogs as GovCogs,
  IconGovStar as GovStar,
  IconGovUser as GovUser,
  IconGovUsers as GovUsers,
  IconUserSuit as UserSuit,
  IconUserGraduate as UserGraduate,
  IconPresenter as Presenter,
  IconGovFile as GovFile,
  IconGovFileText as GovFileText,
  IconGovFileO as GovFileO,
  IconGovFileTextO as GovFileTextO,
  IconFileWord as FileWord,
  IconFileExcel as FileExcel,
  IconFileContract as FileContract,
  IconGovBuilding as GovBuilding,
  IconStatueLiberty as StatueLiberty,
  IconLibertyBell as LibertyBell,
  IconWashingtonMonument as WashingtonMonument,
  IconPentagon as PentagonGov,
} from "@/components/icons/GovIcon";

// Namespace para uso dinâmico (IconPicker e similares)
import * as FluentIcons from "@fluentui/react-icons";
export { FluentIcons as icons };
